export type ChainConfig = {
    id: string;
    name: string;
    subscanHost: string;
    symbol: string;
    status: 'live' | 'test';
};

export const SUPPORTED_CHAINS: ChainConfig[] = [
    { id: 'polkadot', name: 'Polkadot', subscanHost: 'polkadot.api.subscan.io', symbol: 'DOT', status: 'live' },
    { id: 'acala', name: 'Acala', subscanHost: 'acala.api.subscan.io', symbol: 'ACA', status: 'live' },
    { id: 'altair', name: 'Altair', subscanHost: 'altair.api.subscan.io', symbol: 'AIR', status: 'live' },
    { id: 'assethub-kusama', name: 'Assethub Kusama', subscanHost: 'assethub-kusama.api.subscan.io', symbol: 'KSM', status: 'live' },
    { id: 'assethub-polkadot', name: 'Assethub Polkadot', subscanHost: 'assethub-polkadot.api.subscan.io', symbol: 'DOT', status: 'live' },
    { id: 'astar', name: 'Astar', subscanHost: 'astar.api.subscan.io', symbol: 'ASTR', status: 'live' },
    { id: 'autonomys', name: 'Autonomys', subscanHost: 'autonomys.api.subscan.io', symbol: 'AI', status: 'live' },
    { id: 'avail', name: 'Avail', subscanHost: 'avail.api.subscan.io', symbol: 'AVAIL', status: 'live' },
    { id: 'basilisk', name: 'Basilisk', subscanHost: 'basilisk.api.subscan.io', symbol: 'BSX', status: 'live' },
    { id: 'bifrost-kusama', name: 'Bifrost Kusama', subscanHost: 'bifrost-kusama.api.subscan.io', symbol: 'BNC', status: 'live' },
    { id: 'bifrost-polkadot', name: 'Bifrost Polkadot', subscanHost: 'bifrost.api.subscan.io', symbol: 'BNC', status: 'live' },
    { id: 'bridgehub-kusama', name: 'Bridgehub Kusama', subscanHost: 'bridgehub-kusama.api.subscan.io', symbol: 'KSM', status: 'live' },
    { id: 'bridgehub-polkadot', name: 'Bridgehub Polkadot', subscanHost: 'bridgehub-polkadot.api.subscan.io', symbol: 'DOT', status: 'live' },
    { id: 'calamari', name: 'Calamari', subscanHost: 'calamari.api.subscan.io', symbol: 'KMA', status: 'live' },
    { id: 'centrifuge', name: 'Centrifuge Standalone', subscanHost: 'centrifuge-standalone-history.api.subscan.io', symbol: 'CFG', status: 'live' },
    { id: 'centrifuge-parachain', name: 'Centrifuge Parachain', subscanHost: 'centrifuge.api.subscan.io', symbol: 'CFG', status: 'live' },
    { id: 'clover', name: 'Clover', subscanHost: 'clover.api.subscan.io', symbol: 'CLV', status: 'live' },
    { id: 'collectives', name: 'Collectives Polkadot', subscanHost: 'collectives-polkadot.api.subscan.io', symbol: 'DOT', status: 'live' },
    { id: 'coretime-kusama', name: 'Coretime Kusama', subscanHost: 'coretime-kusama.api.subscan.io', symbol: 'KSM', status: 'live' },
    { id: 'coretime-polkadot', name: 'Coretime Polkadot', subscanHost: 'coretime-polkadot.api.subscan.io', symbol: 'DOT', status: 'live' },
    { id: 'creditcoin', name: 'Creditcoin Enterprise', subscanHost: 'cc-enterprise.api.subscan.io', symbol: 'CTC', status: 'live' },
    { id: 'creditcoin-cc3', name: 'Creditcoin CC3', subscanHost: 'creditcoin.api.subscan.io', symbol: 'CTC', status: 'live' },
    { id: 'crust-main', name: 'Crust Mainnet', subscanHost: 'crust.api.subscan.io', symbol: 'CRU', status: 'live' },
    { id: 'crust-parachain', name: 'Crust Parachain', subscanHost: 'crust-parachain.api.subscan.io', symbol: 'CRU', status: 'live' },
    { id: 'darwinia', name: 'Darwinia', subscanHost: 'darwinia.api.subscan.io', symbol: 'RING', status: 'live' },
    { id: 'dbc', name: 'DBC', subscanHost: 'dbc.api.subscan.io', symbol: 'DBC', status: 'live' },
    { id: 'dock-pos', name: 'Dock', subscanHost: 'dock.api.subscan.io', symbol: 'DOCK', status: 'live' },
    { id: 'energywebx', name: 'Energy Web X', subscanHost: 'energywebx.api.subscan.io', symbol: 'EWX', status: 'live' },
    { id: 'enjin-matrix', name: 'Enjin Matrix', subscanHost: 'matrix.api.subscan.io', symbol: 'ENJ', status: 'live' },
    { id: 'enjin-relay', name: 'Enjin Relay', subscanHost: 'enjin.api.subscan.io', symbol: 'ENJ', status: 'live' },
    { id: 'gasp', name: 'Gasp', subscanHost: 'gasp.api.subscan.io', symbol: 'GASP', status: 'live' },
    { id: 'heima', name: 'Heima', subscanHost: 'heima.api.subscan.io', symbol: 'HMA', status: 'live' },
    { id: 'humanode', name: 'Humanode', subscanHost: 'humanode.api.subscan.io', symbol: 'HMND', status: 'live' },
    { id: 'hydradx', name: 'Hydration', subscanHost: 'hydration.api.subscan.io', symbol: 'HDX', status: 'live' },
    { id: 'karura', name: 'Karura', subscanHost: 'karura.api.subscan.io', symbol: 'KAR', status: 'live' },
    { id: 'krest', name: 'Krest', subscanHost: 'krest.api.subscan.io', symbol: 'KREST', status: 'live' },
    { id: 'kusama', name: 'Kusama', subscanHost: 'kusama.api.subscan.io', symbol: 'KSM', status: 'live' },
    { id: 'manta', name: 'Manta', subscanHost: 'manta.api.subscan.io', symbol: 'MANTA', status: 'live' },
    { id: 'moonbeam', name: 'Moonbeam', subscanHost: 'moonbeam.api.subscan.io', symbol: 'GLMR', status: 'live' },
    { id: 'moonriver', name: 'Moonriver', subscanHost: 'moonriver.api.subscan.io', symbol: 'MOVR', status: 'live' },
    { id: 'mythos', name: 'Mythos', subscanHost: 'mythos.api.subscan.io', symbol: 'MYTH', status: 'live' },
    { id: 'origintrail', name: 'Neuroweb', subscanHost: 'neuroweb.api.subscan.io', symbol: 'NEURO', status: 'live' },
    { id: 'peaq-main', name: 'Peaq', subscanHost: 'peaq.api.subscan.io', symbol: 'PEAQ', status: 'live' },
    { id: 'pendulum', name: 'Pendulum', subscanHost: 'pendulum.api.subscan.io', symbol: 'PEN', status: 'live' },
    { id: 'people-kusama', name: 'People Kusama', subscanHost: 'people-kusama.api.subscan.io', symbol: 'KSM', status: 'live' },
    { id: 'people-polkadot', name: 'People Polkadot', subscanHost: 'people-polkadot.api.subscan.io', symbol: 'DOT', status: 'live' },
    { id: 'phala', name: 'Phala', subscanHost: 'phala.api.subscan.io', symbol: 'PHA', status: 'live' },
    { id: 'polymesh', name: 'Polymesh', subscanHost: 'polymesh.api.subscan.io', symbol: 'POLYX', status: 'live' },
    { id: 'reef', name: 'Reef', subscanHost: 'reef.api.subscan.io', symbol: 'REEF', status: 'live' },
    { id: 'robonomics', name: 'Robonomics Standalone', subscanHost: 'robonomics-freemium.api.subscan.io', symbol: 'XRT', status: 'live' },
    { id: 'robonomics-polkadot', name: 'Robonomics Polkadot', subscanHost: 'robonomics.api.subscan.io', symbol: 'XRT', status: 'live' },
    { id: 'shiden', name: 'Shiden', subscanHost: 'shiden.api.subscan.io', symbol: 'SDN', status: 'live' },
    { id: 'sora', name: 'Sora', subscanHost: 'sora.api.subscan.io', symbol: 'XOR', status: 'live' },
    { id: 'space-time', name: 'Space Time', subscanHost: 'sxt.api.subscan.io', symbol: 'SxT', status: 'live' },
    { id: 'spiritnet', name: 'Spiritnet', subscanHost: 'spiritnet.api.subscan.io', symbol: 'KILT', status: 'live' },
    { id: 'stafi', name: 'Stafi', subscanHost: 'stafi.api.subscan.io', symbol: 'FIS', status: 'live' },
    { id: 'tanssi', name: 'Tanssi', subscanHost: 'tanssi.api.subscan.io', symbol: 'TANS', status: 'live' },
    { id: 'unique', name: 'Unique', subscanHost: 'unique.api.subscan.io', symbol: 'UNQ', status: 'live' },
    { id: 'vara', name: 'Vara', subscanHost: 'vara.api.subscan.io', symbol: 'VARA', status: 'live' },
    { id: 'vflow', name: 'Vflow', subscanHost: 'vflow.api.subscan.io', symbol: 'VFLOW', status: 'live' },
    { id: 'zkverify', name: 'zkVerify', subscanHost: 'zkverify.api.subscan.io', symbol: 'ZKV', status: 'live' },
];
